version: '3.8'

networks:
  hadoop-network:
    external: true

volumes:
  jupyter-data:
    
services:
  jupyterhub:
    container_name: "jupyterhub"
    hostname: jupyterhub
    build:
      dockerfile: Dockerfile
      context: ./jupyterhub/
    image: kevinity310/jupyterhub:4.0.2 
    entrypoint: ['./entrypoint.sh', 'jupyterhub']
    ports:
      - '8181:8000'
    networks:
      - hadoop-network
    deploy:
      resources:
        limits:
          cpus: '2'  # Set the desired CPU limit 
          memory: '4G'  # Set the desired memory limit 

  # jupyterhub:
  #   image: jupyterhub/jupyterhub
  #   # This is necessary to prevent the singleton hub from using its service number as its hostname
  #   hostname: jupyterhub
  #   # Permit communication with the host's docker server
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   # Ensure Hub and Notebook servers are on the same network
  #   networks:
  #     - jupyterhub_network
  #   environment:
  #     DOCKER_NETWORK_NAME: jupyterhub_network
  #   # Ensure that we execute on a Swarm manager
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.role == manager

# docker network create --driver overlay jupyterhub_network

# docker compose -f docker-compose-dev.yml build
# docker compose -f docker-compose-dev.yml up -d

  



