version: '3.8'

networks:
  hadoop-network:
    external: true

volumes:
  postgres_hms_data:
    
services:
  trino-coordinator:
    container_name: "trino-coordinator"
    hostname: trino-coordinator
    build:
      dockerfile: Dockerfile
      context: ./trino/trino-coordinator
    image: "kevinity310/trino-coordinator:435"
    ports:
      - "8080:8080"
    command: 
      - "http://trino-coordinator:8080"
      - "coordinator"
    networks:
      - hadoop-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3

  trino-worker:
    build:
      dockerfile: Dockerfile
      context: ./trino/trino-worker
    image: "kevinity310/trino-worker:435"
    command: 
      - "http://trino-coordinator:8080"
    depends_on:
      trino-coordinator:
        condition: service_healthy
    expose:
      - 8080
    networks:
      - hadoop-network
    deploy:
      replicas: 2  # Set the desired number of replicas
      resources:
        limits:
          cpus: '2'  # Set the desired CPU limit 
          memory: '2G'  # Set the desired memory limit 
    healthcheck:
      test: 
        - "CMD-SHELL"
        - "netstat -an | grep LISTEN | grep 8080"
      interval: 10s
      timeout: 5s
      retries: 3
      
# docker compose -f docker-compose-dev.yml up  -scale trino-worker=2  -d
  
# docker compose -f docker-compose-dev.yml build
# docker compose -f docker-compose-dev.yml up -d

  



